### ISSUE TITLE
Text Displaying Poorly

### ISSUE THREAD

**Issue by GreenPhenz** [Renji-XD/texthooker-ui#39] opened 2023-10-26 23:17 UTC
The text comes out from the right behind the settings icon, which makes it impossible to see the current text, changing  "Display Text vertically" or "Reverse Line Order" doesn't change anything.

**Comment by Renji-XD** [comment] 2023-10-27 07:54
hi,

Can you please confirm: You are using a clipboard extension instead of websockets? Then my assumptions is you have not enabled the "Enable external Clipboard Monitor" Option which is required with this way of working (and has otherwise typically similar behavior you described)

Try to enable this
![image](https://github.com/Renji-XD/texthooker-ui/assets/6409827/90c0f16b-5cda-4d03-b395-699eb455fbde)
reload the page and see if the lines are now correctly inserted

In case you are using websockets/still not working can you share what browser you are using / share a screenshot because i am not able to reproduce sth like this

**Comment by Renji-XD** [comment] 2023-11-27 09:02
Closing under the assumption my comment lead to the solution. Feel free to otherwiese reopen with requested information

**Closed by Renji-XD** 2023-11-27 09:02 UTC

**Comment by GreenPhenz** [comment] 2023-11-28 16:17
Hey, sorry I don't check github all that often. Also, I don't know how to / don't think I have the permissions to reopen this issue. But after, enabling "Enable external Clipboard Monitor" the page flashes whenever I try to copy and insert something into it. I'm on chrome, mac.

**Comment by GreenPhenz** [comment] 2023-11-28 16:19
Also, I'm just using the online version

**Comment by Renji-XD** [comment] 2023-11-28 17:10
Hey,

the page by default is only adding text in case you have the timer started (play icon in the top page header).
Alternatively you can also enable this option which adds lines even in a paused state:

![image](https://github.com/Renji-XD/texthooker-ui/assets/6409827/5419433f-3751-49e8-ac35-210f6f203bcc)

If this option is enabled (or you started the timer) and you have enabled the clipboard monitor option as described in my last comment it should work for you

**Comment by GreenPhenz** [comment] 2023-12-02 14:38
OMG TYSM seems to work beautifully now!
